apiVersion: v1
kind: Service
metadata:
  name: doswebstation-service
spec:
  selector:
    app: doswebstation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 
  type: NodePort