apiVersion: v1
kind: ConfigMap
metadata:
  name: settingsmap
data:
  settings.js: |
    var DOSWASMSETTINGS = {
    CLOUDSAVEURL: "",
    DEFAULTIMG: ""
    };

    var rando = Math.floor(Math.random() * Math.floor(100000));
    var script = document.createElement('script');
    script.src = 'script.js?v=' + rando;
    document.getElementsByTagName('head')[0].appendChild(script);
  dosbox-x-for-web.conf: |
    [sdl]
    autolock=false
    showdetails=true
    showmenu=false\
    mouse_wheel_key=1

    [dosbox]
    memsize=16

    [video]
    vmemsize=8
    vesa modelist width limit=0
    vesa modelist height limit=0

    [dos]
    ver=7.1
    hard drive data rate limit=0
    floppy drive data rate limit=0

    [cpu]
    core=dynamic
    cputype=486_slow
    cycles=fixed 30000

    [sblaster]
    sbtype=sb16
    sbbase=220
    irq=7
    dma=1
    hdma=5
    oplmode=auto
    oplrate=44100

    [mixer]
    rate=44100
    blocksize=4096
    prebuffer=50

    [fdc, primary]
    int13fakev86io=true

    [ide, primary]
    int13fakeio=true
    int13fakev86io=true

    [ide, secondary]
    int13fakeio=true
    int13fakev86io=true
    cd-rom insertion delay=4000

    [render]
    scaler=none

    [autoexec]
    SET BLASTER=A220 I7 D1 H5 T6